include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: true
    prefer_single_quotes: true
    public_member_api_docs: true
    lines_longer_than_80_chars: true
    always_specify_types: false